// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zItGJM3r0tSXevVDwv5gdX57W9imBso',
    appId: '1:214911724146:web:95b4cbd9920bb63a31b0eb',
    messagingSenderId: '214911724146',
    projectId: 'cashierbot-for-restaurant',
    authDomain: 'cashierbot-for-restaurant.firebaseapp.com',
    storageBucket: 'cashierbot-for-restaurant.firebasestorage.app',
    measurementId: 'G-VQGFK8592V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wKEu9GZYa8NyY5b7HSviveJDW1RepOA',
    appId: '1:214911724146:android:7227d679015da1d531b0eb',
    messagingSenderId: '214911724146',
    projectId: 'cashierbot-for-restaurant',
    storageBucket: 'cashierbot-for-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvw6zg1Qv_Tlk3ZGr1otv4WCuZVtPCcWo',
    appId: '1:214911724146:ios:8c6852dfb4316fcb31b0eb',
    messagingSenderId: '214911724146',
    projectId: 'cashierbot-for-restaurant',
    storageBucket: 'cashierbot-for-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.cashierBotForRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvw6zg1Qv_Tlk3ZGr1otv4WCuZVtPCcWo',
    appId: '1:214911724146:ios:8c6852dfb4316fcb31b0eb',
    messagingSenderId: '214911724146',
    projectId: 'cashierbot-for-restaurant',
    storageBucket: 'cashierbot-for-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.cashierBotForRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2zItGJM3r0tSXevVDwv5gdX57W9imBso',
    appId: '1:214911724146:web:96be054f403d303831b0eb',
    messagingSenderId: '214911724146',
    projectId: 'cashierbot-for-restaurant',
    authDomain: 'cashierbot-for-restaurant.firebaseapp.com',
    storageBucket: 'cashierbot-for-restaurant.firebasestorage.app',
    measurementId: 'G-KBLJCPE9XF',
  );
}
